flutter-tizen/flutter-tizen

- lib/tizen_build_target.dart
- nuget/Tizen.Flutter.Embedding/FlutterApplication.cs
- nuget/Tizen.Flutter.Embedding/Tizen.Flutter.Embedding.csproj
- Log any unhandled exception raised by the .NET runtime. This is useful when `System.DllNotFoundException` is thrown due to unresolved dependency or missing `.so` files.
- Use `InternalLog` instead of `Log` for better debugging experience on TV
- Bump the nuget package version to 1.0.3
> Log unhandled exceptions

- README.md
- bin/flutter-tizen
- lib/executable.dart
- lib/tizen_device.dart
- lib/tizen_plugins.dart
- All device names are hard-coded as 'Tizen'
- '-d tizen' is set automatically if the device ID is not specified
- Fix an issue with initializing the flutter repo at first launch
- Check if the project is valid before creating an entrypoint file
> Set '-d tizen' automatically

- lib/executable.dart
- lib/tizen_emulator.dart
- lib/tizen_sdk.dart
This pr adds `flutter-tizen emulators` subcommand feature.
+ `flutter-tizen emulators` : lists created emulators.
+ `flutter-tizen emulators --launch <name>`: launches one of the created emulators with the name `<name>`. `<name>` can also be specified as a prefix of one of the emulators.
+ `flutter-tizen emulators --create --name <name>`: creates a new TV or wearable emulator. If both images are installed, TV profiles have priority over wearable ones. If multiple platform versions of the same profile are installed, the one with the highest version will be chosen.
Limitation
+ `flutter-tizen emulators -h` help message currently describes about creating Android emulators.
+ Android Studio(AVD Manager) must be installed for the command to work.
Both limitations can be resolved by creating …
> Add 'emulators' subcommand to flutter-tizen

- lib/tizen_device.dart
Me and swift-kim came to the conclusion that this way is best without any upstream modification.
```bash
flutter-tizen devices
8 connected devices:
SM N950N (mobile)                • ce0717175871bf22017e • android-arm64  • Android 9 (API 28)
Linux (desktop)                  • linux                • linux-x64      • Linux
Web Server (web)                 • web-server           • web-javascript • Flutter Tools
Chrome (web)                     • chrome               • web-javascript • Google Chrome 87.0.4280.66
Tizen W-6.0-circle-x86 (mobile)  • emulator-26121       • flutter-tester • Tizen 6.0 (emulator)
Tizen T-samsung-5.5-x86 (mobile) • emulator-26111       • flutter-tester • Tizen 5.5 (emulator)
Tizen M-6.0-x86 (mobile)         • emulator-26101       • flutter-tester • Tizen 6.0 …
```
> Use model id as tizen device name

- doc/commands.md
- lib/executable.dart
- lib/tizen_artifacts.dart
- lib/tizen_build_target.dart
- lib/tizen_builder.dart
- lib/tizen_device_discovery.dart
- lib/tizen_doctor.dart
- lib/tizen_emulator.dart
- lib/tizen_sdk.dart
- Make more use of context overrides instead of singletons
- Rename TizenDevices to TizenDeviceDiscovery
- Unsupport Android emulators in TizenEmulatorManager to suppress
exceptions when Android SDK is missing
- Fix a state error when no platform images are available
- Replace parseIniLines with parseIniFile to avoid a naming conflict
- Make use of TizenWorkflow in tizen_emulator.dart
- General clean-ups
> Misc changes and clean up

- lib/tizen_device_discovery.dart
Tested in https://regexr.com with this example text:
```
Device ID   device   Model
Device_ID	device	Model
Device_ID 	device  Model
Device_ID	  device  Model
```
> Allow tabs when splitting by pattern in pollingGetDevices

- lib/commands/build.dart
- lib/tizen_build_target.dart
- lib/tizen_builder.dart
- lib/tizen_device.dart
- nuget/Tizen.Flutter.Embedding/FlutterApplication.cs
- nuget/Tizen.Flutter.Embedding/Tizen.Flutter.Embedding.csproj
- templates/app/csharp/Runner.csproj
- templates/app/csharp/tizen-manifest.xml.tmpl
- Rename `TizenBuildInfo.profile` to `TizenBuildInfo.securityProfile` for clarity
- Do not use `__DLP_UNIT_TEST_ARG__` to pass engine arguments to an app any more. Instead, the tool writes the arguments to a plain text file `/home/owner/share/tmp/sdk_tools/{packageId}.rpm` before launching an app and the app reads it on launch (and deletes). This is the only workaround that works for any device type including secure protocol devices. I tried to make the file automatically expire after some time period (10 seconds) but failed after all. No side effect or problem has been found so far.
- Increase the embedding nuget version to 1.1.0
- Add Tizen 4.0 support to the app template
- Change the API version to 4.0
- Change the target framework moniker to tizen40
- Change the C# API version to 4
> Fix engine arugments passing on TV devices

- doc/install-tizen-sdk.md
- doc/wsl-guide.md
- lib/tizen_build_target.dart
- lib/tizen_project.dart
- lib/tizen_sdk.dart
- lib/tizen_tpk.dart
- rootstraps/wearable-4.0-device.flutter.xml
- rootstraps/wearable-4.0-emulator.flutter.xml
- rootstraps/wearable-5.5-device.flutter.xml
- rootstraps/wearable-5.5-emulator.flutter.xml
- templates/app/cpp/project_def.prop
- templates/app/cpp/tizen-manifest.xml.tmpl
- templates/plugin/cpp/project_def.prop.tmpl
- Set Tizen 4.0 as a default build platform
- Add Tizen 4.0 rootstraps
- Read target profiles (such as `common-4.0`, `wearable-5.5`) for native builds from tizen-manifest.xml file
- Efficiently read properties from manifest files (`project_def.prop`, `tizen-manifeset.xml`, `author-signature.xml`)
> Enable building plugins for Tizen 4.0

- bin/flutter-tizen
- bin/flutter-tizen.bat
- lib/tizen_doctor.dart
- lib/tizen_sdk.dart
This pr adds support for the Windows and macOS platforms.
- added batch script file to run `flutter-tizen` in cmd without `python3` command
- updated python and dart code to allow running on Windows and macOS.
- updated python and dart code to find files with Windows extension, such as `.exe` and `.bat`
> Add windows&macos platform support

- lib/tizen_device.dart
Problem
Running `flutter-tizen run` hangs on secure_protocol enabled TV device. 
The `flutter-tizen run` command roughly takes the following steps:
- build tpk
- stop the app on target
- install the app on target
- start the app on target
For secure_protocol enabled devices, `sdb shell 0 kill <app_name>`
is executed to stop the app. At this point, if the app is running on the device,
the command will kill the app, otherwise it will report that the app
is already terminated. However, if the app was not even installed
in the first place, the command is irresponsive.
Solution
A quick solution is checking if the app is installed on the device before
running the command to stop the app. This adds about 500ms to the
`flutter-tizen run` command.
> Fix run command hanging for secure protocol device

- bin/flutter-tizen
- bin/flutter-tizen.bat
- lib/commands/create.dart
- Avoid the use of `shell=True` for slightly better performance on Windows
- Do not create a symbolic link to `template_manifest.json` but permanently copy the file to fix a file deletion error on Windows
> Optimize for Windows

- bin/flutter-tizen.bat
On some Windows 10 installation, `where python3` returns `C:\Users\[user]\AppData\Local\Microsoft\WindowsApps\python3.exe` which just redirects to the python installation page in Microsoft Store. Therefore we should double check whether `python3 -V` exits with 9009.
> Improve flutter-tizen.bat script

- .github/workflows/dart.yml
- bin/flutter-tizen
- doc/commands.md
- doc/debug-flutter-tizen.md
- lib/commands/test.dart
- lib/executable.dart
- lib/tizen_plugins.dart
- pubspec.yaml
- Add the `test` command (for unit/command testing) (tests will be added later)
- Add test-related dependencies in pubspec.yaml
- In bin/flutter-tizen, use `flutter pub` instead of `dart pub` to correctly resolve dependencies of flutter_test
- Remove the use of `waitFor` in `TizenExtension.targetFile` as dart:cli is not available when running tests
> Add the test command

- bin/flutter-tizen
- doc/commands.md
- lib/commands/build.dart
- lib/executable.dart
- lib/tizen_builder.dart
- Add `screenshot` and `symbolize` commands
- Support more build options for `build tpk` command
- `--performance-measurement-file`
- `--bundle-sksl-path`
- `--enable-experiment`
- Update docs accordingly
- Fix `-v` option not working as expected (`-h -v` and `doctor -v`)
> Additional commands and build options

- bin/flutter-tizen.bat
This pr fixes a bug when `flutter-tizen` runs `python3.bat` instead of `python3.exe`.
On Windows, running a command `program` in cmd can run either `program.exe` or `program.bat`. If both files exist in the same path, `exe` has precedence.
When the `flutter-tizen.bat` script executes on a system and the command `python3` runs `python3.bat`, the control flow will not return back to `flutter-tizen.bat`. To fix this, the `CALL` command should be used. ([MS Docs Reference](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/call))
In summary, it seems that `exe` runs in the current batch process and `bat` runs on a child batch process, but doesn't return to the parent if the `CALL` command is not used.
To handle both extension files, `CALL` command should always be …
> Fix flutter-tizen driver bat file on windows

- lib/tizen_build_target.dart
- nuget/Tizen.Flutter.Embedding/FlutterApplication.cs
- nuget/Tizen.Flutter.Embedding/Interop.cs
- nuget/Tizen.Flutter.Embedding/Tizen.Flutter.Embedding.csproj
A temporary fix for library loading issue on TV emulator.
> Load libflutter_engine.so before invoking libflutter_tizen.so

- doc/commands.md
- lib/commands/build.dart
- lib/tizen_build_target.dart
- lib/tizen_builder.dart
- lib/tizen_device.dart
- lib/tizen_emulator.dart
- lib/tizen_tpk.dart
- Detect a profile name from a target device and build plugins with a corresponding switch (-DTV_PROFILE or -DWEARABLE_PROFILE) set
- Add a --device-profile option to the "build tpk" command
This patch adds support for plugins like permission_handler which depend on `capi-privacy-privilege-manager` which is not available on TV.
Related to https://github.com/flutter-tizen/plugins/pull/33.
> Define a profile name switch for plugin builds

- lib/tizen_build_target.dart
- nuget/Tizen.Flutter.Embedding/FlutterApplication.cs
- nuget/Tizen.Flutter.Embedding/Interop.cs
- nuget/Tizen.Flutter.Embedding/Tizen.Flutter.Embedding.csproj
`FlutterRotateWindow` is deprecated and does nothing in the current version of the engine.
> Remove the use of FlutterRotateWindow

- doc/commands.md
- lib/executable.dart
- lib/tizen_build_target.dart
- lib/tizen_device.dart
- lib/tizen_device_discovery.dart
- lib/tizen_doctor.dart
- lib/tizen_sdk.dart
Tracking code changes in the upstream framework between 1.22.0-12.1.pre and 1.22.6.
Changed:
- Improve locating Tizen CLI executable
- Remove `getXxxPath()` for consistency with android implementation (`getAdbPath()` has been removed from flutter_tools)
- Generate an error if Tizen CLI package is not installed
- Add the `gen-l10n` command
> Minor updates for 1.22.6

- lib/tizen_device.dart
- lib/tizen_device_discovery.dart
- Decide the `isSupported` value based on the device's API version
- Do not add a device when sdb gives false information (#30)
- More diagnostic messages (e.g. unauthorized, offline)
Fixes #30.
> Improve device detection

- lib/tizen_build_target.dart
- lib/tizen_plugins.dart
- Print the following message if `foobar_tizen` plugin (non-endorsed) is available but only `foobar` is added as a dependency.
```
package_info_tizen is available on pub.dev. Did you forget to add to pubspec.yaml?
path_provider_tizen is available on pub.dev. Did you forget to add to pubspec.yaml?
```
The plugin list is hard-coded and needs update if a new plugin is added to [flutter-tizen/plugins](https://github.com/flutter-tizen/plugins).
- Small refactoring (rename optional parameters of `findTizenPlugins`)
Suggested by @bbrto21 🎉
> Warn if a Tizen plugin is available

- lib/tizen_build_target.dart
- lib/tizen_builder.dart
This is a sub-pr that will allow small future diffs in pr #47 (Reduce Build time using cache files)
To use the cache build system of `FlutterBuildSystem`, we must retain the output files of `Target` during multiple build commands. However, due to a packaging bug, the current implementation deletes the output folder({PROJECT_ROOT}/build/tizen) in `TizenBuilder.buildTpk`.
https://github.com/flutter-tizen/flutter-tizen/blob/942b24847a205da7e9a76c264dfdb861c02cede2/lib/tizen_builder.dart#L80-L82
After deleting the output folder, `TizenBuilder.buildTpk` calls `FlutterBuildSystem.build` which is where the cache files are looked up to determine if a `Target` requires a rebuild. 
https://github.com/flutter-tizen/flutter-tizen/blob/942b24847a205da7e9a76c264dfdb861c02cede2/lib/tizen_builder.dart#L13 …
> Retain dotnet output

- lib/tizen_emulator.dart
An exception is thrown when there exists an emulator image whose
profile is not both TV and wearable (e.g. mobile).
This change was originally part of #56, but made into a separate PR for clarity.
> Fix emulators command crashes

- templates/app/cpp/project_def.prop
When the toolchain is changed, the linker option "-Wl,-E" is omitted.
Due to this, performance degradation occurred by launching the app using exec() in the candidate process.
Add "-Wl,-E" to linker option of cpp template so that main() symbol are added to the dynamic symbol table,
and can be used in candidate process.
| Applying  "-Wl,-E" linker option   |   Startup Time  |
|:-:|:-:|
| X                                 |  1162 ms              |
| O |  811 ms |
#57
> add linker option "-Wl,-E" to remove regression

- lib/tizen_build_target.dart
- lib/tizen_builder.dart
Altering different build modes doesn't generate expected tpks
- debug -> release : output tpk contains debug binaries because `{OUTPUT_DIR}/flutter_assets` directory still contains them when `DotnetTpk.build()` or `NativeTpk.build()` is called.
- release -> debug: output tpk doesn't contain debug binaries because `TizenAssetBundle.build()` is not reinvoked due to caching. Debug binaries must be specified in `TizenAssetBundle.outputs`, see `DebugAndroidApplication` in `android.dart`.
- x86 -> arm, arm -> x86: arch string is not provided to `Enviroment` in `TizenBuilder.buildTpk()`.
- create DebugTizenAssetBundle and ReleaseTizenAssetBundle.
Both targets must inherit AssetBundle. (See Debug
AndroidApplication and AotAndroidAssetBundle in android.dart)
- Package tpk after FlutterBuildSystem …
> Fix the following bugs

- lib/tizen_plugins.dart
Hybrid plugins may need some extra initialization in Dart code
(e.g. for federated plugins to instantiate platform interfaces).
This change may be required by the notifications plugin currently being investigated by @nojinjeong.
> Allow plugins to define both pluginClass and dartPluginClass

- lib/tizen_build_target.dart
- lib/tizen_builder.dart
- lib/tizen_project.dart
- lib/tizen_sdk.dart
~~:warning: : This pr should be merged after #61~~
This change caches plugin build sources so that plugins are rebuilt only when it needs to.
I've tested for following cases:
- adding new plugin dependency in `pubspec.yaml`
- removing existing plugin dependency in `pubspec.yaml`
- changing existing plugin version in `pubspec.yaml`
- changing the plugin source code when the plugin project is listed as a path dependency in `pubspec.yaml`
The cached sources are:
- inputs: 
- files in `engine/common/client_wrappers`
- files in `engine/common/public`
- `engine/tizen-<arch>-<mode>/libflutter_tizen.so`
- `rootstrap/wearable-<api-version>-<type>.flutter.xml`
- files in `tizen/inc`, `tizen/src`, and the `project_def.prop` file
- outputs: the compiled plugin `.so` files
> Cache plugin sources for build efficiency

- lib/tizen_build_target.dart
Plugin build depends on `profile` and `api-version` values set in the `tizen-manifest.xml` file.
> [Bug fix] Cache tizen_manifest.xml file for plugin build

- lib/tizen_build_target.dart
- lib/tizen_project.dart
- templates/plugin/cpp/project_def.prop.tmpl
The tool will check lib/${arch} directory for dependent binaries and copy them to the output tpk.
Directory names in the plugin project must be armel for arm and i586 for x86.
Currently, I don't know why Tizen cli chooses specifically armel for arm and i586 for x86.
~~- [ ] adding new so files in lib directory during plugin development has caching issues which forces plugin developers to run `flutter-tizen clean`.~~ This turned out is not an issue.
> Support plugins that have dependent binaries

- lib/tizen_builder.dart
- lib/tizen_project.dart
Fixes a null reference exception when running the build command in a plugin project directory. The root cause is `_createEntrypoint` not checking the validity of project properly. The correct behavior is printing this error:
```
Target file "lib/main.dart" not found.
```
> Ensure tizen-manifest.xml exists for app project

- lib/tizen_build_target.dart
Solves issue #74.
It seems that dotnet cli or the build script that is run by the cli doesn't remove empty directories when updating `tpkroot`. I cannot think of a way to fix this without changing the behavior of the dotnet build, a quick solution is deleting `tpkroot` before running dotnet build.
> Clear tpkroot directory before dotnet build

- lib/tizen_build_target.dart
- lib/tizen_builder.dart
- lib/tizen_sdk.dart
- Create a copy of rootstrap manifest instead of creating a symlink
- Also some refactoring
Fixes this error when building Tizen plugins on Windows:
```sh
FileSystemException: Cannot create link, path = 'C:\Apps\tizen-studio\tools\smart-build-interface\plugins\wearable-4.0-device.flutter.xml' (OS Error: A required privilege is not held by the client.
, errno = 1314)
```
Even with this patch still some errors will be thrown when running Tizen native builds on Windows. I'll fix them up soon in a separate patch. → #82
> Fix permission denied error on Windows when building plugins

- templates/app/cpp/tizen-manifest.xml.tmpl
Inspired by @wscho77's comment in https://github.com/flutter-tizen/flutter-tizen/pull/62#issuecomment-804634261, I measured the effect of setting the `hw-acceleration` attribute in tizen-manifext.xml of a simple counter sample app:
```sh
Application                              STIME     PSS     RSS
com.example.native_no_hw_accel            1621   24638   49368
com.example.native_hw_accel               1576   26611   53068
Application                              STIME     PSS     RSS
com.example.native_no_hw_accel             880   26134   40690
com.example.native_hw_accel                846   28654   44938
Application                              STIME     PSS     RSS
com.example.native_no_hw_accel             585   36259   50355
com.example.native_hw_accel                485   37841 …
```
> Enable HW acceleration for native projects by default

- embedding/csharp/FlutterApplication.cs
- embedding/csharp/Tizen.Flutter.Embedding.csproj
- lib/commands/build.dart
- lib/tizen_build_target.dart
- lib/tizen_builder.dart
- lib/tizen_device.dart
This change is preparation for fixing the plugin destruction bug (#90) by reducing discrepancy between the native and .NET TPK structures. I want to apply the same plugin architecture for both native and .NET build targets.
The code diff looks a little bit messy due to indentation changes but there are no other changes than those related to "targetArch". The exception is `TizenAotElf` - we no longer need the custom `build()` method if targeting only a single arch.
> Unsupport building TPK for multiple archs

- lib/tizen_build_target.dart
- lib/tizen_builder.dart
- lib/tizen_plugins.dart
- lib/tizen_project.dart
- lib/tizen_tpk.dart
- templates/plugin/cpp/src/log.h.tmpl
- templates/plugin/cpp/src/projectName_plugin.cc.tmpl
[Before]
- (Native) Plugins are compiled as part of the runner executable.
- (.NET) Plugins are built separately into each .so and loaded by the runner (managed DLL) via P/Invoke. This results in the error stated by #90, because each plugin creates its own `PluginRegistrarManager` instance and tries to register its destruction handler to the embedder.
[After]
- Plugins are compiled into a single file `libflutter_plugins.so` regardless of the app type.
Changelog:
- Re-write the `TizenPlugins` build target
- Update `DotnetTpk.build()` and `NativeTpk.build()` accordingly and clean up
- Remove the `TizenLibrary` class and merge it with `TizenPlugin`
- Change the TPK output directory (from `build/tizen` to `build/tizen/tpk`)
- Wrap the plguin class in the plugin template with an unnamed …
> Compile native plugins into a single shared object

- embedding/cpp/flutter_app.cc
- embedding/cpp/tizen_log.h
- Add missing `va_end()` in `tizen_log.h`
- Check if the target file exists in `ParseEngineArgs()`
> Misc changes to embedding/cpp

- embedding/csharp/Tizen.Flutter.Embedding.csproj
- lib/commands/clean.dart
- lib/commands/create.dart
- lib/commands/packages.dart
- lib/tizen_build_target.dart
- lib/tizen_plugins.dart
- lib/tizen_project.dart
- templates/app/csharp/NuGet.Config
- templates/app/csharp/Runner.csproj
- templates/template_manifest.json
Reference Tizen.Flutter.Embedding by project reference instead of package reference in `Runner.csproj`.
In this way, developers can easily compile and debug C# code (the runner and Tizen.Flutter.Embedding) using the .NET CLI and IDEs (such as Visual Studio).
Notable changes:
- Implement `ensureReadyForTizenTooling()`
- `TizenProject.ensureReadyForPlatformSpecificTooling()` creates a `Runner.csproj.user` file next to `Runner.csproj` which is managed by Visual Studio and flutter-tizen and not version controlled
- Remove `NuGet.Config`
- Update `_knownPlugins` with newly added plugins
Although this change does not break existing projects, it is recommended to re-generate Tizen projects using `flutter-tizen create`. The use of `PackageReference` and `FlutterEmbeddingVersion` in …
> Reference Tizen.Flutter.Embedding via ProjectReference

- lib/tizen_tpk.dart
- Throw and exit if unzipping failed.
- Tell the user what to do:<p>
```
An error occurred while processing a file: build/tizen/tpk/com.example.dotnet_no_hw_accel-1.0.0.tpk
You may delete the file and try again.
```
Fixes #107.
> Exit immediately if a tpk file is corrupted

- embedding/cpp/flutter_app.cc
- rootstraps/wearable-4.0-arm.flutter.xml
- rootstraps/wearable-4.0-x86.flutter.xml
- rootstraps/wearable-5.5-arm.flutter.xml
- rootstraps/wearable-5.5-x86.flutter.xml
Link libstdc++ statically when building apps or plugins for Tizen 4.0 and 5.5, to remove dependency on GLIBCXX_3.4.26 and use C++17 features without limitations.
Fixes #71.
Notes:
- Is it safe to statically  link libstdc++ (especially for our case)? - Yes, I couldn't find any reason not to.
- This change slightly increases the tpk and storage size of an app (by 0.4 MB and 1 MB respectively).
- The change is not applied when targeting Tizen 6.0+, because libstdc++.so on Tizen 6.0+ is already compatible with C++17.
- The change is not applied when targeting arm64, because there's only Tizen 6.0+ runtime for arm64.
> Link libstdc++ statically

- lib/commands/create.dart
Creating C# application caused failure because of not existing app
directory.
Signed-off-by: Rafal Walczyna <r.walczyna@samsung.com>
> Fix create command for C# application

- lib/tizen_build_target.dart
* Now, FLUTTER_PLUGIN_EXPORT macro works as intended
Signed-off-by: Boram Bae <boram21.bae@samsung.com>
> Add visibility hidden as plugin build flag

- templates/plugin/cpp/src/log.h.tmpl
As suggested in https://github.com/flutter-tizen/plugins/pull/111#pullrequestreview-667883789.
> Simplify the __MODULE__ macro definition

- lib/tizen_doctor.dart
- lib/tizen_sdk.dart
Fixes the doctor command crash when the `sdk.version` file is corrupted.
This fixes the error in #142, but doesn't really help fixing the root cause of the error.
> Fix doctor crash when validating Tizen Studio version

- lib/tizen_build_target.dart
- lib/tizen_builder.dart
> Create tpkroot manually when building native app on Windows

- lib/executable.dart
- lib/tizen_doctor.dart
- Displays Tizen tool and engine revisions.
- Displays the .NET SDK version currently in use.
```
$ flutter-tizen doctor -v
[✓] Flutter (Channel unknown, 2.2.1, on Linux, locale C.UTF-8)
• Flutter version 2.2.1 at /home/swift/Git/flutter-tizen/flutter
• Framework revision 02c026b03c (5 weeks ago), 2021-05-27 12:24:44 -0700
• Engine revision 0fdb562ac8
• Dart version 2.13.1
[✓] Tizen toolchain - develop for Tizen devices
• Framework revision 4756304f13 (2 minutes ago), 2021-07-01 17:25:16 +0900
• Engine revision a67e79d07d
• Tizen Studio 4.1 at /home/swift/tizen-studio
• .NET SDK 5.0.300 at /usr/bin/dotnet
```
> Improve the doctor -v output

- lib/commands/precache.dart
- lib/executable.dart
context: #156
Use the 'precache` command to download the tizen engine artifacts as follows:
```bash
flutter-tizen precache  # default artifacts including tizen
flutter-tizen precache --tizen  # explicit artifacts
flutter-tizen precache -a   # all artifacts
```
> Implement precache command for tizen

- lib/tizen_doctor.dart
- lib/tizen_sdk.dart
Issue: The `sdk.version` file is not generated under some circumstances, likely after installing Tizen Studio through the CLI installer.
Changes:
- Let the doctor not complain when the SDK version is not found.
- Use an instance of `Version` to validate the .NET SDK version.
> Do not validate the Tizen SDK version when sdk.version is missing

- lib/tizen_device.dart
Currently an app is installed only once on TV emulator when uninstalling and installing (e.g. due to certificate change) an already installed app. This may lead to the notorious library loading error (https://github.com/flutter-tizen/flutter-tizen/issues/50).
- Make sure the app is installed twice.
- Apply https://github.com/flutter/flutter/pull/67936 (change the functions order and un-nest if blocks).
- Check the uninstallation result.
- Use `Version` when comparing the package API version and the device API version.
> Install TPK twice when uninstalling and re-installing (TV emulator)

- lib/commands/precache.dart
fixed #165 
- release the lock of the cache after updating tizen's engine artifacts
> Release cache lock after updating tizen cache

- lib/commands/build.dart
- lib/commands/drive.dart
- lib/commands/run.dart
- lib/commands/test.dart
- lib/tizen_cache.dart
fix #169
- Add a mixin `TizenRequiredArtifacts` to override `requiredArtifacts`  of `FlutterCommand`.
- Apply the mixin to `build`, `run`, `drive`, `test` commands
> Set requiredArtifacts to drive, test commmands

- lib/tizen_build_target.dart
- lib/tizen_sdk.dart
- Change `getUnixPath` into an extension method `_PathUtils.toPosixPath`.
- Make `getDefaultPathVariable` private.
- Move `getTizenCliArch` to `tizen_sdk.dart`.
> Make functions in tizen_build_target.dart private

- lib/commands/build.dart
Also make `_validateBuild()` private.
e.g.
```sh
flutter-tizen build tpk -pwearable
```
is identical to
```sh
flutter-tizen build tpk --device-profile wearable
```
> Add an alias of --device-profile to BuildTpkCommand

- lib/commands/test.dart
- lib/executable.dart
Allows injecting dart plugins for `flutter-tizen test integration_test`. It's sort a hack, I'm open to better suggestions.
Contributes to #168.
You can test with plugins that require dart code: `package_info_plus`, `connectivity_plus`, ...
> Support dart plugins in test command

- lib/executable.dart
- lib/tizen_build_target.dart
- lib/tizen_device.dart
- lib/tizen_device_discovery.dart
- lib/tizen_doctor.dart
- lib/tizen_emulator.dart
- lib/tizen_plugins.dart
- lib/tizen_sdk.dart
- lib/tizen_tpk.dart
- Reduce the use of `globals` for improved testability.
- Clean-ups for https://github.com/flutter-tizen/flutter-tizen/issues/172.
- Convert factory constructors into static methods.
- Remove unused classes `Certificate` and `SecurityProfile`.
> Various refactoring

- lib/tizen_project.dart
Fixes a null reference error when `Runner.csproj.user` file is corrupted (which is expected to be a very rare case). My previous implementation was incorrect.
Before:
```
Overwriting Runner.csproj.user...
NoSuchMethodError: The getter 'children' was called on null.
Receiver: null
Tried calling: children
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      XmlDescendantsIterator.push (package:xml/src/xml/navigation/descendants.dart:31:23)
#2      new XmlDescendantsIterator (package:xml/src/xml/navigation/descendants.dart:27:5)
#3      XmlDescendantsIterable.iterator (package:xml/src/xml/navigation/descendants.dart:18:37)
#4      WhereTypeIterable.iterator (dart:_internal/iterable.dart:860:64)
#5      WhereIterable.iterator (dart:_internal/iterable.dart:423:62)
#6 …
```
> Handle corrupted Runner.csproj.user properly

- lib/build_targets/package.dart
- lib/build_targets/plugins.dart
- lib/tizen_sdk.dart
- templates/plugin/cpp/project_def.prop.tmpl
- Support linking user static libraries. (Currently only shared libraries are supported).
- Move the `-std=c++17` option to the rootstrap definition.
- Update `project_def.prop` of the plugin template to use a wildcard (`src/*.cc`).
> Allow plugins to link against static libraries

- lib/build_targets/package.dart
- lib/build_targets/plugins.dart
- lib/build_targets/utils.dart
- lib/tizen_plugins.dart
- lib/tizen_sdk.dart
- templates/plugin/cpp/project_def.prop.tmpl
Implements #193.
- Each plugin is built as a static library, and included when the final shared object (`libflutter_plugins.so`) is built.
- Because the target project type is now `staticLib`, linker-specific properties defined in `project_def.prop` do not apply. However, you can still place your libs in `lib` or arch-specific directories under it, such as `lib/arm` and `lib/armel`. The libs will be automatically included during linking even though they are not defined anywhere.
- `lib/arm/libstatic.a` precedes `lib/libstatic.a` if they both exist.
cc @WonyoungChoi
The inputs and outputs of the `tizen_native_plugins` target include:
(Inputs)
- `flutter-tizen/lib/build_targets/plugins.dart`
- `flutter-tizen/lib/tizen_sdk.dart`
- `APP_DIR/.packages` (to create a list of plugins to build)
- …
> Rework the native plugin builder

- lib/tizen_device.dart
- lib/vscode_helper.dart
Context: https://github.com/flutter-tizen/flutter-tizen/issues/190#issuecomment-897563757
Automatically creates or updates `.vscode/launch.json` file in the project directory to provide a debug configuration for the VS Code debugger. If the project is an example app of another plugin or module project, `.vscode/launch.json` in the parent directory is also created or updated.
Usage:
1. Run an app in either debug or profile mode using the `flutter-tizen run` command. (You can optionally specify the `--start-paused` option.)
2. Once the app is launched, open the **Run and Debug** menu in VS Code and choose **flutter-tizen: Attach (project_name)** from available configurations.
3. Press Run (▷) or F5 to attach to the running app.
4. Try breakpoints, widget inspector, etc.
> Support attaching a debugger in VS Code

- lib/build_targets/package.dart
- lib/executable.dart
- lib/tizen_osutils.dart
- pubspec.yaml
Implement `TizenOperatingSystemUtils.unzip()` which doesn't use `ArchiveFile.isFile` to check whether an ArchiveFile is a file on Windows.
Fixes #198.
> Fix OperatingSystemUtils.unzip() on Windows

- lib/tizen_sdk.dart
Contributes to #143.
The version attribute of the generated rootstrap definition is used as part of the output TPK name when building a multi app. This change lets the attribute have a meaningful value.
```sh
com.example.multi_app_flutter-null_armel_Debug.tpk
com.example.multi_app_Tizen-4.0_armel_Debug.tpk
```
> Set a proper version for the generated rootstrap definition

- embedding/cpp/include/flutter_app.h
- embedding/csharp/FlutterApplication.cs
- embedding/csharp/FlutterServiceApplication.cs
I think we can now provide stable APIs for setting Dart entry points.
The entry points can be set before the `Run()` method is called on app instances.
Example (C++):
```cpp
App app;
app.SetDartEntrypoint("anotherMain");
return app.Run(argc, argv);
```
Example (C#):
```csharp
var app = new App();
app.DartEntrypoint = "anotherMain";
app.Run(args);
```
Contributes to #143.
cc @pkosko
> Make Dart entrypoint setters public

- lib/build_targets/package.dart
- lib/tizen_sdk.dart
- Create `TizenSdk.package()` and `TizenSdk.buildApp()`.
- The native TPK builder throws an error if no security profile could be found. I tried replacing `tizen build-app` with `tizen build-native` and `tizen package -r [service_tpk] -- [ui_tpk]` but it wasn't successful (the `package` command removes certificates in the output TPK).
- Improve the mechanism for locating `outputTpk`.
cc @pkosko
> Minor refactoring for NativeTpk.build()

- doc/configure-device.md
- doc/linux-install.md
- doc/macos-install.md
- doc/windows-install.md
- embedding/cpp/.gitignore
- embedding/cpp/project_def.prop
- lib/build_targets/package.dart
- lib/build_targets/plugins.dart
- lib/build_targets/utils.dart
- lib/tizen_sdk.dart
`project_def.prop` files accept `USER_SRCS` as a space-separated list of source paths. As a result, compiling the C++ embedding or cpp_client_wrapper fails if the path to flutter-tizen root directory contains any space character. This change works around the limitation by using only relative paths in `project_def.prop` files.
Fully fixes https://github.com/flutter-tizen/plugins/issues/104.
Related PR: https://github.com/flutter-tizen/flutter-tizen/pull/120
p.s. I also left a question in https://github.sec.samsung.net/RS-TizenStudio/home/issues/201.
Also fixes https://github.com/flutter-tizen/flutter-tizen/issues/218.
> Allow spaces in the path to the flutter-tizen installation directory

- lib/build_targets/package.dart
Currently building **native apps** in **release mode** fails because output TPKs generated by the Tizen builder do not have the build mode suffix is their names:
- Debug mode: `[PACKAGE_ID]_[ROOTSTRAP_VERSION]_[BUILD_ARCH]_Debug.tpk`
- Release mode: `[PACKAGE_ID]_[ROOTSTRAP_VERSION]_[BUILD_ARCH].tpk` 
This PR partially reverts https://github.com/flutter-tizen/flutter-tizen/pull/213.
> Fix the output TPK resolution mechanism

- lib/tizen_plugins.dart
- pubspec.yaml
Find entry points functions from the main dart file and inject to the generated main file.
Resolves the limitation mentioned in https://github.com/flutter-tizen/flutter-tizen/pull/171 ("The use of custom entrypoints may break ...").
Note that this change doesn't take account of all possible uses of the `vm:entry-point` pragma described in https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md#syntax. Only functions are allowed and the second parameter of `@pragma` is not honored.
@jkpu @pkosko
See also: The AST analyzer (https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/doc/tutorial/ast.md)
> Enable the simultaneous use of Dart plugins and custom Dart entrypoints

- lib/tizen_device.dart
Added two conditions.
- `Terminate appId`: Just for debugging purpose. Not normally expected.
- `is already Terminated`: When running integration tests on TV emulator, a process exists earlier than running the kill command (I'm not sure why), resulting in the following `Failed to stop app` error.
```
All tests passed.
I/ConsoleMessage(13931): flutter: 00:03 +6: (tearDownAll)
I/ConsoleMessage(13931): flutter: 00:03 +7: All tests passed!
Failed to stop app
E/ConsoleMessage(13931): appcore: disconnect wl2_display
```
I also considered changing the kill command `app_launcher -k` to `app_launcher -t` but didn't apply, to be always safe.
> Check the app termination result correctly

- lib/tizen_plugins.dart
A lint warning is generated because `_NullaryFunction` is referenced only once unless multiple entry points exist.
> Ignore avoid_private_typedef_functions in generated_main.dart

- lib/commands/test.dart
- lib/executable.dart
- lib/tizen_sdk.dart
- pubspec.yaml
- test/commands/create_test.dart
- test/commands/test_test.dart
- test/general/tizen_device_test.dart
- test/src/fake_tizen_sdk.dart
Major changes:
- Refactor `test.dart`.
- Remove `TizenTestWrapper` and replace with `TizenTestRunner` which implements `FlutterTestRunner`, in order to improve testability. `TizenTestWrapper` cannot be tested because it directly invokes `test.main`.
- Add `test_test.dart`.
Additional changes:
- Reduce the use of `globals` in `TizenSdk` to improve testability.
- Create a common `FakeTizenSdk` class for use by multiple tests (later).
- Minor cleanups.
> Add tests for test.dart

- lib/build_targets/package.dart
- lib/executable.dart
- lib/tizen_builder.dart
- lib/tizen_plugins.dart
- test/general/build_targets/plugins_test.dart
- test/general/tizen_builder_test.dart
- test/src/test_build_system.dart
- Create a class `PackageBuilder` to enable testing `TizenBuilder.buildTpk`.
- Add tests for `tizen_builder.dart` and `build_targets/plugins.dart`.
The total test coverage as of this PR is 39.8% (612 of 1538 lines).
> Add tizen_builder_test.dart and plugins_test.dart

- embedding/csharp/Tizen.Flutter.Embedding.Tests/Channels/MethodChannelTests.cs
- embedding/csharp/Tizen.Flutter.Embedding.Tests/Channels/StandardMethodCodecTests.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/DefaultBinaryMessenger.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/IMethodCodec.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/MethodCall.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/MethodChannel.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/StandardMethodCodec.cs
- embedding/csharp/Tizen.Flutter.Embedding/FlutterException.cs
- embedding/csharp/Tizen.Flutter.Embedding/MissingPluginException.cs
- #127
- Add `MethodChannel`, `StandardMethodCodec` and related classes
- Add tests for the added classes
```c#
var channel = new MethodChannel("test_method_channel");
channel.SetMethodCallHandler(async (call) =>
{
if (call.Method == "method1")
{
// handle the "method1" method and return a result
return new ArrayList() { 1, "TEST_STRING", true };
}
return null;
});
```
> embedding/csharp: Add MethodChannel and related classes

- lib/tizen_plugins.dart
- pubspec.yaml
This change relands https://github.com/flutter-tizen/flutter-tizen/pull/228 which has been reverted by https://github.com/flutter-tizen/flutter-tizen/pull/249, because exported entry points are tree-shaken and in turn discarded in release builds. i.e. `export '{{mainImport}}'` only works for debug builds.
The issue can be reproduced with the tizen_app_control example app in [plugins](https://github.com/flutter-tizen/plugins/tree/master/packages/tizen_app_control).
```
$ flutter-tizen run --release
...
Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
E/ConsoleMessage(21086): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'serviceMain' …
```
> Rewire all Dart entry points in generated_main.dart

- lib/executable.dart
- lib/tizen_cache.dart
- Add a environment variable `TIZEN_ENGINE_GITHUB_RUN_ID` to download the engine artifacts from `Github Actions` builds.
```sh
$ TIZEN_ENGINE_GH_RUN_ID=1424305677 flutter-tizen build tpk
```
- `Github CLI` is used for downloading the artifacts. It should be installed first.
- Change name of the exising varaible for Azure. `AZURE_BUILD_ID` -> `TIZEN_ENGINE_AZURE_BUILD_ID`.
> Add a variable to download engine artifacts from Github Actions.

- lib/commands/create.dart
The `git restore` command requires Git 2.23 and is not generally available on some old Linux distributions.
Reported by @haesik.
> Replace git restore with git checkout

- doc/commands.md
- lib/executable.dart
The command is not relevant for Tizen app development.
> Unsupport the custom-devices command

- lib/executable.dart
- lib/tizen_device_discovery.dart
- lib/tizen_device_manager.dart
Part of https://github.com/flutter-tizen/flutter-tizen/issues/286.
`TizenDeviceManager` cannot be migrated to null safety right now so has been moved to a new file `tizen_device_manager.dart`.
> Migrate tizen_device_discovery.dart to null safety

- lib/tizen_emulator.dart
- lib/tizen_sdk.dart
- test/general/build_targets/plugins_test.dart
- test/general/tizen_sdk_test.dart
- test/src/fake_tizen_sdk.dart
- Implement `parseIniFile` as a replacement for `parseIniLines` to avoid linter warnings.
- Add `tizen_sdk_test.dart` and simplify `plguins_test.dart` in favor of it. (More tests will be added to `tizen_sdk_test.dart` later.)
- `FakeTizenSdk.buildNative` generates a dummy output lib based on the project's `project_def.prop`.
> Add tests for tizen_sdk.dart and organize plguins_test.dart

- lib/build_targets/package.dart
- lib/build_targets/plugins.dart
- lib/build_targets/utils.dart
- lib/tizen_plugins.dart
- test/general/build_targets/plugins_test.dart
- Revert https://github.com/flutter-tizen/flutter-tizen/pull/125, because the limitation has been relieved by https://github.com/flutter-tizen/flutter-tizen/pull/195 and the workaround is no longer necessary.
- Remove support for `sharedLib` plugin projects completely. The `sharedLib` project type has been deprecated for a while since https://github.com/flutter-tizen/flutter-tizen/pull/195 and it's time to remove support for it.
This change makes plugin code easily debuggable in VS Code (https://github.com/flutter-tizen/plugins/issues/295#issuecomment-999292257).
> Remove temporary workarounds in plugins.dart

- lib/tizen_device.dart
- Make `sdbCommand()` private.
- Rename variables `deviceVersion` to `platformVersion` for clarity.
- Make `_writeEngineArguments()` come before `startApp()`.
> Minor cleanups for tizen_device.dart

- lib/tizen_artifacts.dart
Fixes https://github.com/flutter-tizen/flutter-tizen/issues/309.
> Fix getArtifactPath crash when arguments are null

- lib/build_targets/application.dart
- lib/tizen_artifacts.dart
- lib/tizen_build_info.dart
- lib/tizen_builder.dart
- Specify the `platform` argument of `Source.artifact(Artifact.genSnapshot)` so that a correct gen_snapshot artifact is resolved as a dependency of `TizenAotElf`.
- Set `environment.engineVersion` to null when a local engine is being used.
- (Refactoring) Move `getArchForTargetPlatform` and `getTargetPlatformForArch` into `tizen_build_info.dart`.
This change doesn't have any effect for normal users because source artifact paths are resolved only when using a local engine:
https://github.com/flutter/flutter/blob/2.8.1/packages/flutter_tools/lib/src/build_system/source.dart#L169-L183
Additional note (why we use both `TargetPlatform.tester` and `TargetPlatform.android*` in our code):
- `TargetPlatform.tester` is used to identify the device type (i.e. `Device.targetPlatform`).
- …
> Let TizenAotElf respect the target platform

- lib/tizen_plugins.dart
- test/general/build_targets/plugins_test.dart
- test/general/tizen_plugins_test.dart
- Specify the argument `sdkPath` for `AnalysisContextCollection` to allow the Dart analyzer to resolve the SDK path correctly during tests.
- Update the known plugins list.
- Add `tizen_plugins_test.dart` to verify Dart and C++/C# plugin registrants generation.
> Add tests for tizen_plugins.dart

- .gitattributes
- bin/flutter-tizen-gdb
- bin/internal/gdbserver
- lib/tizen_device.dart
- test/general/tizen_device_test.dart
Replaces the previous PR https://github.com/flutter-tizen/flutter-tizen/pull/312. Resolves https://github.com/flutter-tizen/plugins/issues/295.
Adds the `flutter-tizen-gdb` script for native debugging support. The script by default starts `gdbserver` on a connected device and waits for user input to perform additional operations.
Example:
```sh
$ cd my_app
$ sdb root off
$ sdb shell app_launcher -k com.example.my_app
$ sdb shell app_launcher -e com.example.my_app
$ flutter-tizen-gdb
pkg api_version: 4.0
Attached; pid = 6115
Listening on port 37375
Available commands:
r Run GDB client
p Print launch.json configuration
v Open this project in VS Code
q Quit
For detailed usage, see: https://github.com/flutter-tizen/flutter-tizen/wiki/Debugging-app's-native-code
Enter a command:
```
Entering …
> Support native debugging

- lib/tizen_project.dart
- templates/service-app/csharp/Runner.csproj
- templates/ui-app/csharp/Runner.csproj
- test/general/tizen_project_test.dart
- Bump to `Tizen.NET.Sdk` 1.1.7
- Remove unnecessary `DebugType` property from `Runner.csproj`. This setting is a remnant of Mono.
- Remove empty PropertyGroup element from initial `Runner.csproj.user` content.
- Exclude `Runner.csproj.user` file from the clean target because it can be used by other IDEs.
> Cleanup Runner.csproj and Runner.csproj.user

- lib/tizen_project.dart
- User can modify the c# application project name, not the fixed name `Runner.csproj`.
- This is a necessary modification to obtain the name of the Plugin project later.
> Support flexible dotnet project name

- lib/tizen_emulator.dart
- test/general/tizen_emulator_test.dart
- test/src/fake_tizen_sdk.dart
- Use `em-cli`'s `list-platform` and `list-vm` commands to obtain platform and emulator information and do not directly parse `.ini` and `.xml` files.
- Add tests for `TizenEmulatorManager`/`TizenEmulator` and the newly added function `parseEmCliOutput`.
- (minor change) `TizenEmulatorManager` accepts the `dummyAndroidWorkflow` argument to allow testing the class without context.
> Simplify tizen_emulator.dart and add tests

- lib/build_targets/plugins.dart
- lib/tizen_plugins.dart
- lib/tizen_project.dart
- test/general/tizen_plugins_test.dart
- A part of #333 
- Add `namespace` key in `pubspec.yaml` of the plugin.
- Add dotnet plugin registration code in `GeneratedPluginRegistrant.cs`.
- Generate `obj/Runner.csproj.flutter.props`, `obj/Runner.csproj.flutter.targets`  to refer the dotnet plugin projects at build time.
- Generate xxx.csproj.user files of dependent dotnet plugins.
```yaml
flutter:
plugin:
platforms:
tizen:
namespace: Plugins.Tests
pluginClass: HelloPlugin
fileName: HelloPlugin.csproj
```
example plugin: https://github.com/WonyoungChoi/hello_plugin
> Support dotnet plugin tooling

- lib/commands/create.dart
- templates/multi-app/cpp/service/tizen-manifest.xml.tmpl
- templates/multi-app/cpp/ui/tizen-manifest.xml.tmpl
- templates/multi-app/lib/main.dart.tmpl
- templates/plugin/csharp/.gitignore
- templates/plugin/csharp/pluginClass.cs.tmpl
- templates/plugin/csharp/pluginClass.csproj
- templates/service-app/cpp/tizen-manifest.xml.tmpl
- templates/service-app/csharp/tizen-manifest.xml.tmpl
- templates/ui-app/cpp/tizen-manifest.xml.tmpl
- templates/ui-app/csharp/tizen-manifest.xml.tmpl
- test/commands/create_test.dart
- A part of #333.
Support creating a dotnet plugin project.
To create a dotnet plugin,
```sh
flutter-tizen create -t plugin --platforms tizen --tizen-language csharp my_plugin
```   
- Add new template files for dotnet plugin
- Refactor `TizenCreateCommand`
- Override `createTemplateContext()` to provide tizen related context values.
- Override `validateCommand()` to verify arguments.
- Override `generateApp()` to generate example app in C# always.
- Cleanup `runCommand()`.
- Copy templates with language suffix.
- Use `tizenIdentifier` instead of `androidIdentifier` in template files.
- Apply variable default value of `--tizen-language`.
- `cpp` if template type is `plugin`, otherwise `csharp`
> Add plugin/csharp template

- lib/build_targets/application.dart
- lib/build_targets/package.dart
- lib/executable.dart
- lib/tizen_builder.dart
- test/general/build_targets/application_test.dart
- test/general/build_targets/package_test.dart
- test/general/tizen_builder_test.dart
- Generate the asset bundle (`flutter_assets`) in `buildDir` instead of `outputDir` to deal with the issue described in https://github.com/flutter-tizen/flutter-tizen/pull/51.
- Remove `PackageBuilder` and add `DebugTizenApplication`/`ReleaseTizenApplication` to dependencies of `DotnetTpk`/`NativeTpk`.
- Rename the target `Package` to `TizenPackage` and make it always unskippable.
> Remove PackageBuilder and use a unified BuildSystem

- embedding/csharp/Tizen.Flutter.Embedding.Tests/Channels/MethodChannelTests.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/MethodChannel.cs
- templates/plugin/csharp/pluginClass.cs.tmpl
- Add a overloading of `MethodChannel.SetMethodCallHandler` for sync callback.
- Remove unnecessary delegate definition of `MethodCallHandler` to avoid hiding the callback method signature.
- Add `MethodChannel.UnsetMethodCallHandler()`. `ArgumentNullException` will be thrown if handler parameter of `SetMethodCallHandler()` is null.
```csharp
MethodChannel channel = new MethodChannel("foo");
channel.SetMethodCallHandler((call) => "bar");  // sync callback
channel.SetMethodCallHandler(async (call) => "bar"); // async callback
channel.SetMethodCallHandler((call) => Task.FromResult<object>("bar"));  // async callback
```
> Add MethodChannel.SetMethodCallHanlder() for sync callback

- lib/build_targets/application.dart
This change was not included in https://github.com/flutter-tizen/flutter-tizen/pull/349 and, in turn, the build system always complains about missing output files.
> Fix outputs paths of the DebugTizenApplication target

- bin/flutter-tizen-gdb
Add the `--download-symbols` command to `flutter-tizen-gdb` to support downloading right debug symbols for the user device architecture and the target engine version.
The following command will download two zip files and extract them to `symbols/` in the current directory.
```sh
$ flutter-tizen-gdb --download-symbols
Downloading tizen-arm-debug_symbols.zip... Done
Downloading tizen-arm-release_symbols.zip... Done
The downloaded symbols can be found at "symbols/".
```
The detailed instruction on how to use the symbols can be found at:
https://github.com/flutter-tizen/flutter-tizen/wiki/Debugging-app's-native-code#resolving-engine-and-embedder-symbols
> Support downloading engine and embedder symbols

- bin/internal/shared.bat
- bin/internal/shared.sh
Fixes https://github.com/flutter-tizen/flutter-tizen/issues/368.
Effectively there should be no regression in the total fetch time because `flutter --version` also fetches all tags by default. Actually `git clone --depth=1` + `git fetch --tags` takes longer than a single `git clone`.
> Do not shallow clone the Flutter repo

- lib/build_targets/package.dart
- lib/commands/clean.dart
- lib/tizen_application_package.dart
- lib/tizen_artifacts.dart
- lib/tizen_build_system.dart
- lib/tizen_device.dart
- lib/tizen_emulator.dart
- pubspec.yaml
`super` parameters was introduced as a new language feature in [Dart 2.17](https://medium.com/dartlang/dart-2-17-b216bfc80c5d).
The `use_super_parameters` linter rule will be enabled by default in the upstream analysis options in the future. This change is a preparation for that.
> Prepare for turning on use_super_parameters

- bin/flutter-tizen-gdb
This change was missing from https://github.com/flutter-tizen/flutter-tizen/pull/366.
> Align flutter-tizen-gdb with the new engine version format

- lib/build_targets/package.dart
The target library that needs to be referenced must be located behind it.
So change the order, --whole-archive is not needed anymore.
> build_targets: Remove --whole-archive flag and realign libs

- embedding/cpp/flutter_engine.cc
- embedding/cpp/include/elm_flutter_view.h
- embedding/cpp/include/flutter_app.h
- embedding/cpp/include/flutter_engine.h
- embedding/cpp/include/flutter_service_app.h
- embedding/csharp/Tizen.Flutter.Embedding/FlutterApplication.cs
- embedding/csharp/Tizen.Flutter.Embedding/FlutterServiceApplication.cs
- Remove unused `NotifyAppIsInactive` and `NotifyAppIsDetached` from `FlutterEngine`.
- Switch access modifiers of some protected members of `FlutterApp`/`FlutterServiceApp` to private.
- Update stale documentation.
> Remove NotifyAppIsInactive and NotifyAppIsDetached

- lib/build_targets/package.dart
- lib/build_targets/plugins.dart
- test/general/build_targets/plugins_test.dart
Copy a plugin's `res` directory to `res/[plugin_name]` in the output TPK during app build.
This feature has been requested by @xiaowei-guan. He wants to selectively dlopen a shared library (bundled with a plugin) depending on the current platform version at runtime.
**Known issue:** The incremental build may fail (plugins do not rebuild) if a new lib or res file has been added after an initial build without modification to any other source file. Possible solutions include:
1. Always force rebuild plugins (this affects the overall build time), or
2. Support the "sharedLib" plugin type (which has been deprecated as of https://github.com/flutter-tizen/flutter-tizen/pull/98) and let the user explicitly specify lib names in `project_def.prop`. (This is a partial solution since res files are …
> Copy plugin resource files to app TPK

- lib/build_targets/embedding.dart
- lib/build_targets/package.dart
- lib/build_targets/plugins.dart
- lib/tizen_sdk.dart
- lib/tizen_tpk.dart
- test/general/build_targets/embedding_test.dart
- test/general/build_targets/package_test.dart
- Extract `NativeEmbedding` from `NativeTpk` as a separate build target.
- Make `TizenManifest.apiVersion` nullable.
This change is a preparation for https://github.com/flutter-tizen/flutter-tizen/issues/397. This also reduces the total build time by up to 5 secs.
> Build NativeEmbedding separately from NativeTpk

- doc/commands.md
- lib/build_targets/package.dart
- lib/commands/build.dart
- lib/tizen_builder.dart
- test/commands/build_test.dart
- test/general/build_targets/package_test.dart
- test/general/tizen_builder_test.dart
Contributes to https://github.com/flutter-tizen/flutter-tizen/issues/397.
Usage:
```sh
flutter-tizen build module -pmobile --debug --target-arch x86
```
By default, the following files are generated in the output directory. (The output directory can be specified with the `--output-dir` option.)
```sh
build/tizen/module/
├── inc
│   ├── elm_flutter_view.h
│   ├── flutter
│   │   ├── basic_message_channel.h
│   │   ├── binary_messenger.h
│   │   ├── byte_streams.h
│   │   ├── encodable_value.h
│   │   ├── ...
│   │   ├── plugin_registry.h
│   │   ├── standard_codec_serializer.h
│   │   ├── standard_message_codec.h
│   │   ├── standard_method_codec.h
│   │   └── texture_registrar.h
│   ├── flutter_app.h
│   ├── flutter_engine.h
│   ├── flutter_export.h
│   ├── flutter.h
│   ├── …
```
> Add the build module command

- lib/forwarding_log_reader.dart
- pubspec.yaml
- test/general/forwarding_log_reader_test.dart
Let `ForwardingLogReader` attempt to establish a logging service even after the designated time has elapsed.
This is useful when debugging Flutter modules that are not started immediately after app launch.
> Try connecting to the device logger indefinitely

- lib/tizen_sdk.dart
- test/general/tizen_sdk_test.dart
Resolves https://github.com/flutter-tizen/flutter-tizen/issues/410.
The warning is shown in the console output and often confuses the user.
> Do not display the TV SDK not found warning

- .github/workflows/test.yml
Simply checks whether the tool can build C++ and C# apps successfully.
This helps identifying major regressions and p0 issues such as https://github.com/flutter-tizen/flutter-tizen/pull/384.
More complex integration tests (e.g. apa behavior and performance analysis) might be added in the future.
> Add app build test to the CI

- lib/build_targets/embedding.dart
- lib/build_targets/package.dart
- lib/build_targets/plugins.dart
- lib/build_targets/utils.dart
- lib/tizen_plugins.dart
- test/general/build_targets/embedding_test.dart
- test/general/build_targets/package_test.dart
- test/general/build_targets/plugins_test.dart
- test/general/tizen_plugins_test.dart
Resolves https://github.com/flutter-tizen/plugins/issues/417. This is also an alternative solution of https://github.com/flutter-tizen/flutter-tizen/pull/392.
- Support both "staticLib" and "sharedLib" type plugins.
- "sharedLib" type plugins are built into individual shared objects (`lib{plugin_name}.so`). They can specify arbitrary linker options in their `project_def.prop`. In case of `webview_flutter_tizen`, for example:<p>
```ini
USER_LIBS = pthread lightweight-web-engine.flutter tuv
USER_LIB_DIRS = lib/${BUILD_ARCH}
USER_LFLAGS =
```
- Let `TizenPlugins` depend on `NativeEmbedding` (whose build output contains compiled cpp_client_wrapper).
- Add missing input dependencies to `NativeEmbedding`.
- Change the output directory of `libflutter_plugins.so` from …
> Support sharedLib type native plugins

- lib/build_targets/plugins.dart
The embedding lib must come before the embedder lib in the compiler options as we've done in 940c43a8a2577f6efe395f565e061ffd21120d10. Otherwise some projects (such as [this](https://github.sec.samsung.net/f-project/flutter-webrtc/tree/main/packages/flutter-webrtc/tizen)) generate an error.
> Change the linking order in TizenPlugins

- embedding/cpp/elm_flutter_view.cc
- embedding/cpp/include/elm_flutter_view.h
Adds `ElmFlutterView::engine()` which returns a pointer to the view's engine instance.
This is a preparation for https://github.com/flutter-tizen/flutter-tizen/pull/416#discussion_r943087246.
Important notice: The plugin registration API will also be changed as follows.
```patch
@@ -64,7 +64,7 @@ class App {
flutter_view = new ElmFlutterView(box, 720, 400);
if (flutter_view->RunEngine()) {
-      RegisterPlugins(flutter_view);
+      RegisterPlugins(flutter_view->engine());
elm_box_pack_end(box, flutter_view->evas_object());
}
```
@bbrto21 How do you think of this change? I decided not to make additional changes to `FlutterEngine::Create` or `ElmFlutterView::SetEngine`.
> Add engine getter to ElmFlutterView

- templates/module/csharp/.tizen.tmpl/tizen-manifest.xml.tmpl
- templates/service-app/csharp/tizen-manifest.xml.tmpl
- templates/ui-app/csharp/tizen-manifest.xml.tmpl
The `api-version` attribute of the `ui-application` element in `tizen-manifest.xml` is never used and we can safely remove it according to https://github.com/flutter-tizen/flutter-tizen/pull/420#discussion_r944099917.
> Update tizen-manifest.xml of C# app templates

- embedding/cpp/elm_flutter_view.cc
- embedding/cpp/flutter_app.cc
- embedding/cpp/flutter_service_app.cc
- embedding/cpp/include/flutter_app.h
- embedding/cpp/include/flutter_engine.h
- embedding/cpp/include/flutter_service_app.h
- embedding/csharp/Tizen.Flutter.Embedding/ElmFlutterView.cs
- embedding/csharp/Tizen.Flutter.Embedding/FlutterApplication.cs
- embedding/csharp/Tizen.Flutter.Embedding/FlutterEngine.cs
- embedding/csharp/Tizen.Flutter.Embedding/FlutterServiceApplication.cs
- embedding/csharp/Tizen.Flutter.Embedding/Interop/Interop.cs
- embedding/csharp/Tizen.Flutter.Embedding/Plugins/IPluginRegistry.cs
Contributes to https://github.com/flutter-tizen/flutter-tizen/issues/351.
Changes:
- Add the C# version of C++'s `ElmFlutterView` class.
- Add `IsRunning` to `FlutterApplication` and `FlutterServiceApplication` and replace `Engine.IsValid` with `IsRunning` (for overall consistency).
- Add missing documentation.
- Minor fixes and formatting.
Usage:
```csharp
var flutterView = new ElmFlutterView(box);
if (flutterView.RunEngine())
{
GeneratedPluginRegistrant.RegisterPlugins(flutterView);
box.PackEnd(flutterView.EvasObject);
}
...
if (flutterView.IsRunning)
{
// The view must be explicitly destroyed by user.
flutterView.Destroy();
}
```
> Add the C# implementation of ElmFlutterView

- lib/build_targets/package.dart
- test/general/build_targets/package_test.dart
The current native module builder implementation (https://github.com/flutter-tizen/flutter-tizen/pull/405) generates `libembedding_cpp.a` in the output directory's `lib` directory.
```sh
build/tizen/module/
└── lib
└── libembedding_cpp.a
```
This results in the file being included in the container app's TPK if no extra care is taken. This change makes the file to be generated in either `Debug` or `Release` (which is determined by the builder from the build mode).
The app developer should add `${BUILD_CONFIG}` (which is transformed into `Debug` or `Release` by the Tizen CLI builder) to the container app's library searching path as follows.
```patch
USER_INC_DIRS = inc
USER_OBJS =
USER_LIBS = embedding_cpp flutter_tizen_mobile flutter_plugins
-USER_LIB_DIRS = lib
+USER_LIB_DIRS = lib …
```
> Prevent libembedding_cpp.a from being included in TPK

- embedding/csharp/.editorconfig
- embedding/csharp/Tizen.Flutter.Embedding.Tests/Channels/BinaryCodecTests.cs
- embedding/csharp/Tizen.Flutter.Embedding.Tests/Channels/EventChannelTests.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/BinaryCodec.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/DefaultBinaryMessenger.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/EventChannel.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/IEventSink.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/IMessageCodec.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/IMethodCodec.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/MethodChannel.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/StandardMessageCodec.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/StandardMethodCodec.cs
- embedding/csharp/Tizen.Flutter.Embedding/Channels/StringCodec.cs
- embedding/csharp/Tizen.Flutter.Embedding/Common/StreamExtensions.cs
- embedding/csharp/Tizen.Flutter.Embedding/FlutterApplication.cs
- embedding/csharp/Tizen.Flutter.Embedding/FlutterEngine.cs
- embedding/csharp/Tizen.Flutter.Embedding/Interop/Interop.cs
- embedding/csharp/Tizen.Flutter.Embedding/Plugins/DotnetPluginRegistry.cs
- embedding/csharp/Tizen.Flutter.Embedding/Plugins/FlutterPluginBinding.cs
- embedding/csharp/Tizen.Flutter.Embedding/Plugins/IPluginRegistry.cs
Format the C# embedding code in a consistent manner.
The code has been hand-formatted without assistance by a tool. The `dotnet format` command and the [`.editorconfig`](https://github.com/flutter-tizen/flutter-tizen/blob/master/embedding/csharp/.editorconfig) file are almost useless.
Unlike Dart or C++, there's no universal style rule that can be applied to our C# code. [Google's C# style guide](https://google.github.io/styleguide/csharp-style.html) defines its own unique set of rules that do not comply with the general C# standard. So I tried to make only minimal changes to the existing code:
- Column width: 120
- Indentation: 4 spaces
- Always make a line break with a 4 space indent if arguments do not fit on one line.
> Format C# code

- lib/build_targets/embedding.dart
Fixes a problem of C++ embedding not rebuilding after modifying its source code.
> Add missing inputs to NativeEmbedding

- lib/build_targets/package.dart
- lib/tizen_builder.dart
- lib/tizen_plugins.dart
- templates/module/csharp/.tizen.tmpl/Runner.csproj
- templates/module/csharp/.tizen.tmpl/tizen-manifest.xml.tmpl
- test/general/build_targets/package_test.dart
- test/general/tizen_plugins_test.dart
Contributes to https://github.com/flutter-tizen/flutter-tizen/issues/397.
Building a module:
```sh
$ flutter-tizen create -t module dotnet_module
$ cd dotnet_module
$ flutter-tizen build module -pmobile --debug --target-arch x86
$ flutter-tizen run
```
Importing the module from a container app:
```xml
<PropertyGroup>
<FlutterModuleDir>../dotnet_module/build/tizen/module</FlutterModuleDir>
</PropertyGroup>
<ItemGroup>
<PackageReference Include="Tizen.Flutter.Embedding" Version="1.0.0" />
</ItemGroup>
```
Note: The `Tizen.Flutter.Embedding` nuget will be published after https://github.com/flutter-tizen/flutter-tizen/pull/429 is merged.
> Support building a .NET module

- lib/commands/create.dart
The following error was reported from an engineer at SRI-Delhi.
```powershell
D:\2022>flutter-tizen create .
Failed to run git apply: D:/2022/flutter-tizen/templates/ui-app/.gitignore.patch:13: trailing whitespace.
D:/2022/flutter-tizen/templates/ui-app/.gitignore.patch:14: trailing whitespace.
.vscode/
error: patch failed: packages/flutter_tools/templates/app_shared/.gitignore.tmpl:15
error: packages/flutter_tools/templates/app_shared/.gitignore.tmpl: patch does not apply
```
I couldn't reproduce the error but it seems it occurs under some condition during `git apply` on Windows. This patch prevents the error by supplying the `--whitespace=fix` option to `git apply`.
> Fix the create command trailing whitespace error

- doc/commands.md
- lib/commands/attach.dart
- lib/executable.dart
- lib/tizen_device.dart
- lib/vscode_helper.dart
- test/general/vscode_helper_test.dart
Add the `attach` command again but with a limitation.
This change is for debugging support of module apps (contributes to https://github.com/flutter-tizen/flutter-tizen/issues/351). The `debug-url` should be manually obtained from the device log (dlog) by the user. I tried to automate the procedure but failed for several reasons:
- `TizenDevice.getLogReader` has not enough information to choose between `TizenDlogReader` and `ForwardingLogReader`.
- `dlogutil -c` and `dlogutil -m` are not supported by non-root devices.
- The device log has incorrect timestamps on TV. Also the `getdate` command doesn't provide any timezone information.
> Re-enable the attach command

- lib/build_targets/package.dart
Fixes a bug reported by @bbrto21 where the tool incorrectly copies `libflutter_tizen_mobile.so` instead of `libflutter_tizen_mobile_nui.so` during .NET module build (targeting Tizen 6.5).
The relevant code has accidentally been removed during rebase (due to a conflict between https://github.com/flutter-tizen/flutter-tizen/pull/431 and https://github.com/flutter-tizen/flutter-tizen/pull/418).
> Copy a correct embedder binary during .NET module build

- lib/tizen_sdk.dart
- test/general/tizen_sdk_test.dart
Potentially fixes https://github.com/flutter-tizen/flutter-tizen/issues/441.
Ensures the `make.exe` executable in the msys2 directory is detected first during Tizen CLI build on Windows.
> Change the PATH search order on Windows

- embedding/cpp/flutter_app.cc
- embedding/cpp/flutter_service_app.cc
- embedding/cpp/include/flutter_app.h
- embedding/cpp/include/flutter_service_app.h
- embedding/csharp/Tizen.Flutter.Embedding/ElmFlutterView.cs
- embedding/csharp/Tizen.Flutter.Embedding/FlutterApplication.cs
- embedding/csharp/Tizen.Flutter.Embedding/FlutterEngine.cs
- embedding/csharp/Tizen.Flutter.Embedding/FlutterServiceApplication.cs
- embedding/csharp/Tizen.Flutter.Embedding/Interop/Interop.cs
- embedding/csharp/Tizen.Flutter.Embedding/NUIFlutterView.cs
- embedding/csharp/Tizen.Flutter.Embedding/Tizen.Flutter.Embedding.csproj
- Change private properties to private fields.
- Fix class layout orders. [SA1201](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1201.md) , [SA1202](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1202.md)
- Remove `DartEntrypoint` property of `FlutterApplication` and `FlutterServiceApplication`.
- Simplify `NUIFlutterView.RunEngine()` .
- Remove unused private member `dart_entrypoint_args_` from `FlutterApp` and `FlutterServiceApp`.
> Clean up embedding code

- doc/debug-app.md
- doc/develop-plugin.md
- doc/publish-app.md
Note: https://flutter.dev/docs is automatically redirected to https://docs.flutter.dev so I didn't update the links.
> Update broken links in docs

- templates/plugin/csharp/pluginClass.csproj
Remove unnecessary `PackageReference` for `Tizen.NET` from the C# plugin template. Since the C# plugin project already refers to the `Tizen.NET` package in the `Tizen.NET.Embedding` project being referenced, version conflicts can occur such as follows:
```
/home/zzervb/Tests/FlutterTizenTests/test_plugin/tizen/TestPlugin.csproj : error NU1605: Detected package downgrade: Tizen.NET from 9.0.0.16760 to 4.0.1.14164. Reference the package directly from the project to select a different version. 
/home/zzervb/Tests/FlutterTizenTests/test_plugin/tizen/TestPlugin.csproj : error NU1605:  TestPlugin -> Tizen.Flutter.Embedding -> Tizen.NET (>= 9.0.0.16760) 
/home/zzervb/Tests/FlutterTizenTests/test_plugin/tizen/TestPlugin.csproj : error NU1605:  TestPlugin -> Tizen.NET (>= 4.0.1.14164)
0 Warning(s) …
```
> Remove PackageReference to Tizen.NET from C# plugin template

- lib/build_targets/package.dart
- lib/tizen_project.dart
If the service app build dir of a multi app (`tizen/service/Debug` or `tizen/service/Release`) is not cleaned up before running a build, the following linker error can be generated after switching a profile (e.g. `-pwearable` to `-pmobile`).
```sh
/home/swift/tizen-studio/tools/smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../../../i586-tizen-linux-gnueabi/bin/ld: cannot find
-lappcore-watch
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [/home/swift/tizen-studio/tools/ide/resources/native/Build/makefile.mk:135: Debug/runner_service] Error 1
make[1]: Leaving directory '/home/swift/Git/plugins/packages/tizen_app_control/example/tizen/service'
make: *** …
```
> Do additional cleanup before multi app build

- .github/workflows/release.yml
- embedding/cpp/project_def.prop
- lib/build_targets/embedding.dart
- lib/build_targets/package.dart
- lib/build_targets/plugins.dart
- lib/build_targets/utils.dart
- lib/tizen_sdk.dart
- test/general/build_targets/embedding_test.dart
- test/general/build_targets/plugins_test.dart
Currently it's not very easy to access the Dart VM API from plugin native code because the relevant header and source files must be included in each plugin's source tree. This patch automatically adds `dart_api_dl.c` to the `NativeEmbedding` build target (so it's statically linked with the plugin code) and adds the `dart_api_dl.h` location to the include path during build, making the APIs available to all app and plugin native code:
```cpp
#include <dart_api_dl.h>
intptr_t ImagePickerTizenPluginInitializeDartApi(void *data) {
return Dart_InitializeApiDL(data);
}
```
> Make dart_api_dl.h symbols available to app and plugin code

- lib/build_targets/package.dart
- lib/build_targets/plugins.dart
- lib/tizen_sdk.dart
- test/general/tizen_sdk_test.dart
- test/src/fake_tizen_sdk.dart
Set the `FLUTTER_BUILD_DIR` environment variable during plugin and app build to allow some files to be downloaded to the location when building FlutterFire plugins.
cc @daeyeon @hs0225
> Set FLUTTER_BUILD_DIR environment variable when building plugins

- bin/internal/shared.bat
- bin/internal/shared.sh
The `flutter` command is being called redundantly due to https://github.com/flutter/flutter/commit/2835c3f1161afcd93894324475c72eb66f67a05e.
> Fix flutter_tools.stamp version check

- lib/forwarding_log_reader.dart
The following program results in a decoding error because the `Utf8Decoder` cannot handle the `¦` character.
```dart
import 'dart:convert';
import 'dart:typed_data';
const log = '''
errno = 2 (No such file or directory), LastError = 2
InternalCanonicalizeRealPath fail: /proc/12431/fd/13/lib/.native_image/PluginCsharpPlugin.ni.exe ¦k 2
''';
void main() {
const decoder = Utf8Decoder(allowMalformed: false);
final data = Uint8List.fromList(log.codeUnits);
print(decoder.convert(data));
}
```
> Fix FormatException during log processing

- lib/tizen_builder.dart
- lib/tizen_plugins.dart
- test/commands/build_test.dart
- test/general/tizen_builder_test.dart
- test/general/tizen_plugins_test.dart
Fixes https://github.com/flutter-tizen/plugins/issues/123.
Implements https://github.com/flutter/flutter/issues/98591 for Tizen.
Previously, an app that depends on any _Dart plugin_ (a platform package of a federated plugin that has any Dart implementation) had to explicitly call the `register` method of each plugin to use the plugin in a _background isolate_ as follows.
```dart
compute((_) async {
PathProviderPlugin.register();
print(await getApplicationDocumentsDirectory());
}, null);
```
Now this platform-specific call is no longer necessary, and instead the app can simply call Flutter's `DartPluginRegistrant.ensureInitialized` to initialize all Dart plugins that it depends on.
```dart
compute((_) async {
DartPluginRegistrant.ensureInitialized();
print(await …
```
> Make Dart plugin registrants work on background isolates

- .github/workflows/test.yml
- embedding/csharp/Tizen.Flutter.Embedding.Tests/Tizen.Flutter.Embedding.Tests.csproj
- Upgrade Tizen Studio to 5.5.
- Install missing packages to fix [the CI issue](https://github.com/flutter-tizen/flutter-tizen/actions/runs/6794479025/job/18471171116).
- Update the C# embedding test project TFM to `net6.0`.
> [ci] Upgrade Tizen Studio to 5.5

- embedding/csharp/Tizen.Flutter.Embedding/Channels/StandardMessageHelper.cs
0xffff = 65535
Int16.MaxValue = 32767
So all platform messages, that has size between 32767 and 65532 will raise exception `System.OverflowException: Value was either too large or too small for an Int16`
This PR fix this problem
> Fix OverflowException in StandardMessageHelper

- doc/linux-install.md
- doc/macos-install.md
- doc/windows-install.md
- lib/build_targets/package.dart
- lib/tizen_doctor.dart
- lib/tizen_sdk.dart
- templates/multi-app/cpp/service/.gitignore
- templates/multi-app/cpp/ui/.gitignore
- templates/service-app/cpp/.gitignore
- templates/ui-app/cpp/.gitignore
- test/general/build_targets/package_test.dart
- test/general/tizen_doctor_test.dart
- test/general/tizen_sdk_test.dart
Previously, arbitrary lib and res files provided by an app developer (for a C++ project) could not be included in the output TPK because the `tizen/lib` and `tizen/res` directories were exclusively used by the flutter-tizen tool. However, as of Tizen Studio 5.0 (released last year), it is possible to repackage an existing TPK by [appending any lib and res files](https://github.sec.samsung.net/RS-TizenStudio/home/issues/256) to it using the `-e` parameter.
Directory structure after build:
<table>
<tr><th>Before</th><th>Now</th></tr>
<tr>
<td>
```
tizen/
├── Debug
│   └── ...
├── flutter
│   ├── generated_main.dart
│   └── generated_plugin_registrant.h
├── inc
│   └── runner.h
├── lib
│   ├── libflutter_engine.so
│   └── libflutter_tizen_mobile.so
├── project_def.prop
├── res
│   ├── …
```
> Allow embedding user lib and res in native TPK

- lib/tizen_sdk.dart
The IoT-Headed 6.0 SDK doesn't have a rootstrap for emulator. Use the mobile 6.0 rootstrap instead.
```sh
$ flutter-tizen build tpk --debug --target-arch x86 -p common
target: tizen_cpp_embedding
exception:Error: The rootstrap iot-headed-6.0-emulator.core could not be found.
To install missing package(s), run:
/home/swift/tizen-studio/package-manager/package-manager-cli.bin install IOT-Headed-6.0-NativeAppDevelopment-CLI
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      TizenSdk.getRootstrap (package:flutter_tizen/tizen_sdk.dart:320:7)
#2      NativeEmbedding.build (package:flutter_tizen/build_targets/embedding.dart:103:43)
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:861:27)
<asynchronous suspension>
#4 …
```
> Fix build error when api-version=6.0 and arch=x86

- lib/tizen_device.dart
The TV 8.0 emulator no longer prints `val[ok]` during uninstall.
```sh
00:36 +0: loading /tmp/flutter_tools.YPMDVO/BQGDKV/shared_preferences_test.dart
00:45 +16: (tearDownAll)                                                                                                                                                          
sdb uninstall failed:
uninstall org.tizen.shared_preferences_tizen_example
app_id[org.tizen.shared_preferences_tizen_example] uninstall start
app_id[org.tizen.shared_preferences_tizen_example] uninstalling[11]
app_id[org.tizen.shared_preferences_tizen_example] uninstalling[23]
app_id[org.tizen.shared_preferences_tizen_example] uninstalling[34]
app_id[org.tizen.shared_preferences_tizen_example] uninstalling[46]
app_id[org.tizen.shared_preferences_tizen_example] …
```
> Fix TizenDevice.uninstallApp unexpectedly returning false

- lib/tizen_device.dart
- test/general/tizen_device_test.dart
This PR includes the following changes to reduce the `flutter-tizen run` execution time.
The main idea of the PR is to minimize unnecessary calls to `sdb` commands, which are relatively time-consuming, in order to reduce the overall execution time. 
> When measured on Windows, each execution of `sdb` command takes approximately 800~900ms.
Currently, the target architecture is determined by checking the existence of a specific path (`/usr/lib64`) as below. 
```sh
[   +1 ms] executing: C:\tizen-studio\tools\sdb.exe -s 10000000f2770a98 shell ls /usr/lib64
[ +909 ms] Exit code 0 from: C:\tizen-studio\tools\sdb.exe -s 10000000f2770a98 shell ls /usr/lib64
[        ] ls: cannot access /usr/lib64: No such file or directory
```
This has been modified to utilize the already obtained capability …
> Optimize the `flutter-tizen run` execution time

- lib/tizen_plugins.dart
- Add `flutter_webrtc`, `in_app_purchase`, `video_player` and `webview_flutter`.
- If there is more plugins besides *_tizen, use a different warning output format.
ex)
```
path_provider_tizen is available on pub.dev. Did you forget to add to pubspec.yaml?
shared_preferences_tizen is available on pub.dev. Did you forget to add to pubspec.yaml?
sqflite_tizen is available on pub.dev. Did you forget to add to pubspec.yaml?
[webview_flutter_tizen or webview_flutter_lwe] are available on pub.dev. Did you forget to add to pubspec.yaml?
```
> Update the known plugins list

- lib/build_targets/plugins.dart
related issue: https://github.com/flutter-tizen/flutter-tizen/issues/647
When building the `api-version="10.0"` native plugin using the Tizen 10.0 dev SDK, we found that unintended library dependencies were added. These libraries are not actually used in Flutter and do not exist in TV profile.
Our analysis results show that the compilation's --as-needed option in SDK's makefile is searching for a specific symbol and the dependency is added, so we suspect that this issue comes from the SDK's toolchain's gcc was upgraded.
So, let's add `-lstdc++` first for resolve this issue.
(However `libBrokenLocale.so.1` is still added but it works fine on TV. (libBrokenLocale is not added in all cases.))
This PR is a temporary patch and managed as a known issue.
Test plugin&app: default …
> Fix link error and dependency issue in Tizen 10.0

- .github/workflows/analyze.yml
- .github/workflows/close_issue.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Close issue pages that have been inactive for more than 60 days.
but do not close issues that have a "bug", "enhancement" or "keep" label.
+) And add license information.
> [ci] Add an action to automatically close long-inactived issues
