flutter-tizen/flutter-tizen

lib/tizen_device_discovery.dart

* Change parsing condition for detecting tizen devices
Signed-off-by: MuHong Byun <mh.byun@samsung.com>

Support more tizen devices

---

.github/workflows/dart.yml
README.md
analysis_options.yaml
lib/commands/create.dart
lib/tizen_build_target.dart
lib/tizen_emulator.dart
lib/tizen_sdk.dart
pubspec.yaml

Fix warnings from `dart format` and `dart analyze`. The new CI runs them automatically.

Update analysis_options.yaml and resolve warnings

---

lib/tizen_device.dart

Temporarily disable log filtering on TV

---

lib/tizen_device.dart

Currently lines that do not start with `*/ConsoleMessage(*):` are all being skipped although some of them are parts of multiline messages. Use a similar logic to AdbLogReader to handle them properly.

Handle multiline logs properly

---

README.md
doc/devtools-usage.md
doc/get-started.md
doc/install-tizen-sdk.md
doc/publish-app.md

There are other small changes.

Add publish-app.md

---

rootstraps/wearable-6.0-device.flutter.xml
rootstraps/wearable-6.0-emulator.flutter.xml

There may be someone who needs this.

Add Tizen 6.0 rootstraps

---

lib/tizen_doctor.dart
lib/tizen_emulator.dart
lib/tizen_sdk.dart

Checks the currently installed Tizen Studio version.

Add detailed information in doctor -v messages

---

lib/tizen_emulator.dart

Before:
```
$ flutter-tizen emulators
5 available emulators:
W-5.5-circle-x86         • W-5.5-circle-x86         • Samsung • linux
T-samsung-6.0-x86        • T-samsung-6.0-x86        • Samsung • linux
M-6.0-x86                • M-6.0-x86                • Samsung • linux
W-4.0-circle-x86-preview • W-4.0-circle-x86-preview • Samsung • linux
W-6.0-circle-x86         • W-6.0-circle-x86         • Samsung • linux
```
After:
```
$ flutter-tizen emulators
5 available emulators:
W-5.5-circle-x86         • Wearable Circle • Samsung • linux
T-samsung-6.0-x86        • HD1080 TV       • Samsung • linux
M-6.0-x86                • HD Mobile       • Samsung • linux
W-4.0-circle-x86-preview • Wearable Circle • Samsung • linux
W-6.0-circle-x86         • Wearable Circle • Samsung • linux
```
Also fixes a …

Use deviceTemplate name as an emulator name

---

README.md
doc/configure-device.md
doc/macos-install.md
lib/tizen_doctor.dart
lib/tizen_sdk.dart

Officially adds macOS support.

Add macos-install.md

---

lib/tizen_build_target.dart
lib/tizen_sdk.dart
lib/tizen_tpk.dart

This pr implements certificate constructs that read certificate profile information and locate certificate files from the system. The certificate profiles managed by the certificate manager is written in `tizen-studio-data/profile/profiles.xml`.

Impl certificate constructs

---

lib/tizen_build_target.dart

- Set appropriate PATH before running CLI build
- Use GCC standard (Unix-style) path representation
Fixes this error:
```
PS D:\Git\dummy\plugin_build\example> flutter-tizen build tpk --debug
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Exception: Failed to build plugin_build plugin:
[PLATFORM] Wearable-4.0
[ARCHITECTURE] armel
[COMPILER] LLVM-10.0
[CONFIGURATION] Debug
[SBI] prdefine options =
[SBI] command : cmd /c make.exe -f "C:\Apps\tizen-studio\tools\ide\resources\native\Build\makefile" -r
'make.exe' is not recognized as an internal or external command,
operable program or batch file.
Total time: 00:00:00.172
Building a Tizen application in debug mode...                    1,352ms
The build failed.
```
and also a …

Fix Tizen CLI build on Windows

---

lib/tizen_tpk.dart

This change allows TizenManifest to read Application ID from
<service-application> element as well as <ui-application>.
It is a small step towards supporting [Tizen Service Application](https://docs.tizen.org/application/native/guides/applications/service-app/). It prevents a crash when flutter-tizen installs application which has only `service-application` instead of `ui-application` in `tizen-manifest.xml`.

Add support for <service-application> in TizenManifest

---

embedding/csharp/FlutterApplication.cs
embedding/csharp/Interop.cs
embedding/csharp/Tizen.Flutter.Embedding.csproj
lib/commands/build.dart
lib/tizen_build_target.dart

Engine-side work: https://github.com/flutter-tizen/engine/pull/67
Need to update the engine hash before merging.
Contributes to https://github.com/flutter-tizen/flutter-tizen/issues/86.

Use different embedders for different profiles

---

lib/tizen_build_target.dart

This PR supports plugins with user libraries (such as  [webview_flutter](https://github.com/flutter-tizen/plugins/tree/master/packages/webview_flutter)) for native runner.

Support plugins with user libs for native runner

---

bin/engine.version

The engine version 2.0.1 (4) which has been released recently had a critical performance problem (significantly slow app startup). This new engine release (https://github.com/flutter-tizen/engine/releases/tag/6e859d7) contains a quick fix for it.

Hotfix for engine performance issue

---

lib/tizen_build_target.dart

Currently there is a bug that ignores any code changes. The map function doesn't work as I expected.

Fix TizenPlugins unexpectedly skipping builds

---

embedding/csharp/FlutterApplication.cs
embedding/csharp/Interop.cs
embedding/csharp/Tizen.Flutter.Embedding.csproj
lib/tizen_build_target.dart
lib/tizen_device.dart

This reverts #34 and applies a solution described by https://github.com/flutter-tizen/flutter-tizen/issues/50#issuecomment-831675478.
Fixes #50.

A workaround for library loading issue on TV emulator

---

lib/executable.dart

Before:
```
$ flutter-tizen --version
Flutter 2.0.1 • channel unknown • unknown source
Framework • revision c5a4b4029c (10 weeks ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
```
After:
```
$ flutter-tizen --version
Flutter for Tizen 2.0.1 • revision 8a52219954 (2 minutes ago)
Framework • revision c5a4b4029c (10 weeks ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
```
Please share if you have any better idea!

Support the --version option

---

lib/tizen_device.dart

- Fixes the following error when a device is disconnected while an app is running.
- Small clean-ups.
```
swift@SWIFT:~/Git/dummy/amuapp$ flutter-tizen run --release
Launching lib/main.dart on Tizen rpi3 in release mode...
Building a Tizen application in release mode...                    13.7s
✓ Built build/tizen/tpk/com.example.amuapp-1.0.0.tpk (6.3MB).
Installing build/tizen/tpk/com.example.amuapp-1.0.0.tpk...         21.8s
Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
I/ConsoleMessage( 5834): FlutterApplication.cs: ParseEngineArgs(87) > Enabled: --enable-dart-profiling
E/ConsoleMessage( 5834): Draw call returned Invalid argument.  Expect corruption.
ProcessException: Process exited abnormally:
error: target …
```

Fix ProcessException when device disconnected abnormally

---

.clang-format
.github/workflows/dart.yml

- Add the `.clang-format` file for use by clang-format.
- Run the CI workflow for all branches.

Add .clang-format

---

lib/tizen_build_target.dart

This change mitigates the problem stated by https://github.com/flutter-tizen/plugins/issues/105#issuecomment-848442024, by changing the build directory for plugin builds from the project's flutter_build directory (`[project]/.dart_tool/flutter_build`) to a system temp directory.
By applying this change,
- The location of the app project no longer affects the plugin build.
- The file path length limitation is relieved on Windows. `[plugin_name]/tizen/src/[source_file_name].cc` can be now up to 94 characters long.
Resolves #122.

Fix the long path issue on Windows

---

lib/tizen_device.dart

Fixes https://github.com/flutter-tizen/engine/issues/91.

Add a log filter to skip xkbcommon errors

---

lib/tizen_build_target.dart

- Show a default certificate warning during native app build.
- Capitalize "TPK"s.

Show warning when building a native app with default certificate

---

lib/tizen_device.dart

Contributes to #168 
Allow dlogs to show in `drive` command.
~~Different solution for https://github.com/flutter/flutter/blob/2dc11a85ff26b434bf0dd391097514b005289681/packages/flutter_tools/lib/src/android/android_device.dart#L602-L604. Applying the same solution causes the following error which I can't figure out, so I'm referencing the [iOS logger logic](https://github.com/flutter/flutter/blob/2dc11a85ff26b434bf0dd391097514b005289681/packages/flutter_tools/lib/src/ios/devices.dart#L732-L748).~~
```
/tmp/flutter_tools.VYGBSB/CQKUOL/org.tizen.package_info_plus_tizen_example.rpm   1KB/s (60 bytes in 0.037s)
[        ] executing: /home/hakkyu/tizen-studio/tools/sdb -s emulator-26101 shell app_launcher -s org.tizen.package_info_plus_tizen_example
[ +304 ms] ... successfully launched pid = …
```

Allow dlogs to return after observatory discovery

---

lib/tizen_tpk.dart

Do not chmod TPK contents recursively

---

embedding/csharp/Tizen.Flutter.Embedding.csproj
lib/build_targets/package.dart

Remove deprecated `FlutterEmbeddingVersion` completely.

Remove support for PackageReference

---

lib/build_targets/plugins.dart

Fixes https://github.com/flutter-tizen/plugins/issues/178.

Fix plugin build error on Windows

---

lib/executable.dart

- Enable the `daemon` command and the `--machine` option. The command is hidden by default and not intended for use by general users so I didn't add to `doc/commands.md`.
- Use `LoggerFactory` when creating a Logger instance.

Add the daemon command

---

lib/commands/create.dart

Fixes the issue addressed by https://github.com/flutter-tizen/flutter-tizen/issues/207#issuecomment-906939372.
Commands for testing:
```
flutter-tizen create
flutter-tizen create --list-samples samples.json
flutter-tizen create --app-type multi --tizen-language cpp multi_app
flutter-tizen create --app-type multi --tizen-language cpp --overwrite multi_app
```
cc @pkosko

Do not overwrite the main.dart file

---

lib/vscode_helper.dart

Adding support for non-plugin packages that have example apps.

Fix the example app detection logic

---

embedding/cpp/include/flutter_app.h

Signed-off-by: MuHong Byun <mh.byun@samsung.com>

Fix issues from static analysis

---

.github/workflows/analyze.yml
.github/workflows/test.yml
README.md
embedding/csharp/.editorconfig
embedding/csharp/Tizen.Flutter.Embedding.Tests/Channels/BasicMessageChannelTests.cs
embedding/csharp/Tizen.Flutter.Embedding.Tests/Channels/MethodChannelTests.cs
embedding/csharp/Tizen.Flutter.Embedding.Tests/Channels/StandardMessageCodecTests.cs
embedding/csharp/Tizen.Flutter.Embedding.Tests/Channels/StandardMethodCodecTests.cs
embedding/csharp/Tizen.Flutter.Embedding/Common/PinnedObject.cs

Add the dotnet-format job and dotnet-test job to the CI.

Verify C# code in the CI

---

embedding/csharp/Tizen.Flutter.Embedding.Tests/Channels/EventChannelTests.cs
embedding/csharp/Tizen.Flutter.Embedding/Channels/EventChannel.cs
embedding/csharp/Tizen.Flutter.Embedding/Channels/EventStreamHandler.cs
embedding/csharp/Tizen.Flutter.Embedding/Channels/IEventSink.cs
embedding/csharp/Tizen.Flutter.Embedding/Channels/IEventStreamHandler.cs

- #127 
- Add EventChannel and related classes
- Add tests for EventChannel
```c#
var eventChannel = new EventChannel("test_event_channel");
eventChannel.SetStreamHandler(new EventStreamHandler(
(args, sink) =>
{
Console.WriteLine("OnListen!!");
counter = 0;
timer = new Timer(100);
timer.Elapsed += (sender, e) =>
{
sink.Success("TEST_EVENT " + counter++);
};
timer.Start();
},
(args) =>
{
Console.WriteLine("OnCancel!!");
timer.Stop();
}));
```

embedding/csharp: Add EventChannel and related classes

---

lib/build_targets/plugins.dart
test/general/build_targets/plugins_test.dart

Fixes https://github.com/flutter-tizen/flutter-tizen/issues/277.

Let -lpthread come before any other linking options

---

lib/commands/precache.dart
test/commands/build_test.dart
test/commands/clean_test.dart
test/commands/precache_test.dart
test/commands/test_test.dart
test/src/fakes.dart

Add tests for `build.dart`, `clean.dart` and `precache.dart`.

Add tests for more commands

---

lib/forwarding_log_reader.dart
lib/tizen_device.dart

Part of https://github.com/flutter-tizen/flutter-tizen/issues/286.
The analyzer will fail because this change depends on https://github.com/flutter-tizen/flutter-tizen/pull/292.

Migrate tizen_device.dart and forwarding_log_reader.dart to null safety

---

lib/executable.dart
lib/tizen_doctor.dart

Part of https://github.com/flutter-tizen/flutter-tizen/issues/286.

Migrate tizen_doctor.dart to null safety

---

.github/workflows/test.yml

Print coverage information after running the tool test.
```
Reading tracefile coverage/lcov.info
Summary coverage rate:
lines......: 44.9% (738 of 1643 lines)
functions..: no data found
branches...: no data found
Reading tracefile coverage/lcov.info
|Lines       |Functions  |Branches    
Filename                              |Rate     Num|Rate    Num|Rate     Num
============================================================================
[lib/]
build_targets/application.dart        | 3.1%     64|    -     0|    -      0
build_targets/package.dart            | 2.1%    190|    -     0|    -      0
build_targets/plugins.dart            |81.3%    155|    -     0|    -      0
build_targets/utils.dart              |80.0%     15|    -     0|    -      0
commands/build.dart                   | …
```

Generate a code coverage report

---

lib/tizen_sdk.dart
test/general/tizen_sdk_test.dart

- Tidy up `tizen_sdk.dart`.
- Add more tests to `tizen_sdk_test.dart`.

Additional tests for tizen_sdk.dart

---

lib/tizen_cache.dart

Part of https://github.com/flutter-tizen/flutter-tizen/issues/286 and https://github.com/flutter-tizen/engine/issues/224.
You can set `engine.version` to [`790d2b05053276c3e3eacf6edd9ca628acf7dbe0`](https://github.com/flutter-tizen/engine/releases/tag/790d2b0) to test this change (the artifacts are currently available for Linux only).
cc @WonyoungChoi

Download host platform artifacts

---

lib/tizen_tpk.dart

- Implement `TizenManifest.applicationType` and `TizenTpk.isDotnet`. The properties are not currently used but is preparation for https://github.com/flutter-tizen/plugins/issues/295.
- Refactor: Use `late final` (new in Dart 2.12) to avoid evaluating the same property multiple times.

Add isDotnet property to TizenTpk

---

lib/executable.dart
lib/tizen_builder.dart
lib/tizen_device_manager.dart
lib/tizen_doctor.dart
test/general/tizen_builder_test.dart

Use globals if and only if it makes sense.

Organize the use of globals

---

lib/forwarding_log_reader.dart
lib/tizen_builder.dart
lib/tizen_tpk.dart
lib/vscode_helper.dart
test/general/tizen_device_test.dart
test/general/vscode_helper_test.dart

These changes were originally included in https://github.com/flutter-tizen/flutter-tizen/pull/312 but discarded along with the PR. Let's recycle them.

Minor changes from #312

---

templates/multi-app/lib/main.dart.tmpl
templates/multi-app/pubspec.yaml.patch

Bump to tizen_app_control 0.1.1 and messageport_tizen 0.2.0

Update multi-app template

---

doc/develop-plugin-csharp.md
doc/develop-plugin.md

- #333 
- Add a document "Writing a plugin in C#"

Add a doc "Writing a plugin in C#"

---

doc/commands.md
doc/develop-plugin-csharp.md
doc/develop-plugin.md

- Add some additional information to `commands.md`.
- Update `develop-plugin.md` and `develop-plugin-csharp.md` according to the updated plugin template.
- Reword some content of `develop-plugin-csharp.md` for clarity.
- Replace all "C/C++" with just "C++" in `develop-plugin.md`.

Update plugin-related docs

---

embedding/cpp/elm_flutter_view.cc
embedding/cpp/include/elm_flutter_view.h

Add an API that returns the width and height size of evas_object.
and when resizing, compare the actual size, not the initial size.

Add the ElmFlutterView's width/height getter methods

---

lib/build_targets/package.dart

Fixes the build failure mentioned in https://github.com/flutter-tizen/flutter-tizen/pull/379#issuecomment-1169421471.

Add dependencies for native host

---

embedding/cpp/include/flutter_engine.h
lib/build_targets/package.dart
lib/build_targets/plugins.dart
lib/commands/build.dart
lib/tizen_builder.dart
lib/tizen_tpk.dart
test/general/tizen_builder_test.dart

The tool should not arbitrarily modify `tizen-manifest.xml` files.

Do not modify the content of tizen-manifest.xml

---

templates/multi-app/lib/main.dart.tmpl
templates/multi-app/pubspec.yaml.patch

- Update tizen_app_control to 0.2.0.
- Add dependency on tizen_app_manager.

Update the multi-app template

---

lib/tizen_project.dart

The clean command generates an error for module projects.
```sh
$ flutter-tizen pub get
Running "flutter pub get" in tizen_module...                       309ms
$ flutter-tizen clean
Deleting .tizen...                                                   3ms
FileSystemException: Directory listing failed, path = '/home/swift/Git/dummy/tizen_module/.tizen/' (OS Error: No such file or directory, errno = 2)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      findDotnetProjectFile …
```

Fix the clean command when the project is a module

---

.github/workflows/analyze.yml
.github/workflows/release.yml
.github/workflows/test.yml

The workflow is only run manually on demand (`workflow_dispatch`).

Publish C# embedding as a nuget on nuget.org

---

lib/tizen_device.dart

Fixes the bug stated by https://github.com/flutter-tizen/plugins/pull/454#issuecomment-1267823329.

Fix stopApp not working on TV in case of app/package ID mismatch

---

lib/build_targets/package.dart
test/general/build_targets/package_test.dart

Fixes https://github.com/flutter-tizen/flutter-tizen/issues/456.
Do not use the `-o` (output) option but use the default .NET CLI build directory. The path to the build directory is parsed from the CLI output since the target framework name (e.g. `tizen40`) is unknown to the flutter-tizen tool. The build artifacts (TPK file and tpkroot) are copied to the output directory (`build/tizen/tpk`) after build.

Do not use the output option when running .NET CLI build

---

lib/tizen_plugins.dart

- Add `flutter_app_badger`, `flutter_secure_storage`, and `google_sign_in`.
- Remove `share_plus` (discontinued).
- Remove `video_player` and `webview_flutter` (the Tizen packages may not have the `_tizen` suffix).
- `video_player_videohole`
- `webview_flutter_lwe`

Update the known plugins list

---

lib/forwarding_log_reader.dart

Do not print unnecessary "already rotated" warning messages to the output console on window resize and rotation requests.
Also ignore the "Thread added" and "Thread removed" messages.
Resolves https://github.com/flutter-tizen/engine/issues/348.

Suppress "already rotated" warning messages

---

doc/macos-install.md

Tizen Studio 5.0 now supports Apple Silicon (arm64) hosts.

Update macOS documentation

---

templates/plugin/.gitignore.patch

This should have been included in https://github.com/flutter-tizen/flutter-tizen/pull/244.

Add .gitignore.patch for the plugin template

---

test/general/tizen_device_test.dart

Add basic tests for `TizenDevice.installApp()`, `TizenDevicePortForwarder`.

Add more tests to tizen_device_test.dart

---

bin/flutter-tizen-gdb

Only indentation changes (4 to 2). No code change.
Style guide: https://github.com/flutter-tizen/flutter-tizen/wiki/Style-guide#python

Reformat the flutter-tizen-gdb script

---

.github/workflows/release.yml

Similar to https://github.com/flutter-tizen/plugins/pull/584.

[ci] Use new pub cache location for release

---

embedding/csharp/Tizen.Flutter.Embedding/Channels/StandardMessageHelper.cs

Fix byte conversion in StandardMessageHelper

---

lib/forwarding_log_reader.dart
lib/tizen_build_info.dart
lib/tizen_device_discovery.dart
lib/tizen_sdk.dart

https://github.com/flutter/flutter/pull/144905

Refactor if chains into switch statements

---

lib/commands/build.dart

Reverts some of the changes made incorrectly in #665.

Fix incorrect arch name change
